### ISSUE TITLE
Is there an example ~/nodes file?

### ISSUE THREAD

**Issue by yasuf** [jepsen-io/mongodb#20]
I'm trying to run the tests, but not sure if there is an example ~/nodes file I can use to run them locally.

```
java.io.FileNotFoundException: /Users/username/nodes (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219) ~[na:na]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158) ~[na:na]
	at clojure.java.io$fn__11466.invokeStatic(io.clj:229) ~[clojure-1.10.0.jar:na]
	at clojure.java.io$fn__11466.invoke(io.clj:229) ~[clojure-1.10.0.jar:na]
	at clojure.java.io$fn__11379$G__11372__11386.invoke(io.clj:69) ~[clojure-1.10.0.jar:na]
	at clojure.java.io$fn__11478.invokeStatic(io.clj:258) ~[clojure-1.10.0.jar:na]
	at clojure.java.io$fn__11478.invoke(io.clj:254) ~[clojure-1.10.0.jar:na]
	at clojure.java.io$fn__11379$G__11372__11386.invoke(io.clj:69) ~[clojure-1.10.0.jar:na]
	at clojure.java.io$fn__11440.invokeStatic(io.clj:165) ~[clojure-1.10.0.jar:na]
	at clojure.java.io$fn__11440.invoke(io.clj:165) ~[clojure-1.10.0.jar:na]
```

**Comment by rhishikeshj** [comment]
The `nodes` is a simple list of names nodes that you are running.
For example, in a docker-compose based setup, the node names are `n1...n5`
So the nodes file would be 

```
n1
n2
n3
n4
n5
```

Create it directly on the control node's console, or by creating it in the `JEPSEN_ROOT` dir if you have set one.

```
JEPSEN_ROOT=<path-to-your-test-folder> ./bin/up --dev
```
